package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/confluentinc/confluent-kafka-go/v2/kafka"
	"github.com/redis/go-redis/v9"
)

// FraudAlert matches the payload contract generated by Zone 3 workers
type FraudAlert struct {
	TransactionID string   `json:"transaction_id"`
	CardNumber    string   `json:"card_number"`
	Violations    []string `json:"violations"`
	SwipeCount    int64    `json:"swipe_count"`
	Timestamp     int64    `json:"timestamp"`
}

const (
	kafkaBroker       = "localhost:9092"
	interdictionGroup = "fraud-interdiction-group"
	fraudAlertsTopic  = "fraud-alerts"
)

func main() {
	log.Println("🛡️ Active Interdiction Shield Initializing...")

	// 1. Establish connection to Redis to execute active card freezing
	rdb := redis.NewClient(&redis.Options{
		Addr: "localhost:6379",
	})
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	if err := rdb.Ping(ctx).Err(); err != nil {
		log.Fatalf("❌ Interdiction Engine failed to connect to Redis: %v", err)
	}
	log.Println("✅ Interdiction Engine connected to Redis cache mapping layer.")

	// 2. Initialize Apache Kafka Consumer for the alert topic stream
	consumer, err := kafka.NewConsumer(&kafka.ConfigMap{
		"bootstrap.servers": kafkaBroker,
		"group.id":          interdictionGroup,
		"auto.offset.reset": "earliest",
	})
	if err != nil {
		log.Fatalf("❌ Failed to instantiate interdiction consumer: %v", err)
	}
	defer consumer.Close()

	if err := consumer.SubscribeTopics([]string{fraudAlertsTopic}, nil); err != nil {
		log.Fatalf("❌ Failed to subscribe to alert channel %s: %v", fraudAlertsTopic, err)
	}

	log.Println("🚀 Active Interdiction Shield Online. Awaiting security threats...")

	// 3. Graceful Shutdown Signal Interceptor
	sigchan := make(chan os.Signal, 1)
	signal.Notify(sigchan, syscall.SIGINT, syscall.SIGTERM)

	// 4. Autonomous Defense Loop
	run := true
	for run {
		select {
		case sig := <-sigchan:
			fmt.Printf("\n⚠️ Intercepted system signal %v: Powering down defense grid...\n", sig)
			run = false
		default:
			msg, err := consumer.ReadMessage(100 * time.Millisecond)
			if err != nil {
				if err.(kafka.Error).Code() == kafka.ErrTimedOut {
					continue
				}
				log.Printf("❌ Alert ingestion stream error: %v\n", err)
				continue
			}

			// De-serialize the incoming fraud packet data contract
			var alert FraudAlert
			if err := json.Unmarshal(msg.Value, &alert); err != nil {
				log.Printf("❌ Failed to decode incoming threat packet format: %v\n", err)
				continue
			}

			fmt.Println("\n=================================================================")
			log.Printf("🚨 [CRITICAL THREAT CAUGHT] Transaction ID: %s\n", alert.TransactionID)
			log.Printf("💳 Target Compromised Card: %s\n", alert.CardNumber)
			
			for _, violation := range alert.Violations {
				log.Printf("⚠️ Rule Breach Context: %s\n", violation)
			}

			// Execution of Simulated Mitigations (Active Countermeasures)
			executeSimulatedSMSNotification(alert.CardNumber, alert.Violations)
			executeActiveCardProfileFreezing(rdb, alert.CardNumber)
			fmt.Println("=================================================================")
		}
	}
}

// simulate a real-time external communications webhook call
func executeSimulatedSMSNotification(cardNumber string, violations []string) {
	log.Printf("🛰️  Simulating Cellular Webhook Dispatch...")
	log.Printf("📱 [SMS SENT TO CARDHOLDER] Alert! We detected suspicious activity on your card ending in %s. Breaches flagged: %v. Reply NO to block.", 
		cardNumber[len(cardNumber)-4:], violations)
}

// actively manipulate user metadata cache state to prevent subsequent fraud loops
func executeActiveCardProfileFreezing(rdb *redis.Client, cardNumber string) {
	ctx := context.Background()
	profileKey := fmt.Sprintf("card:%s", cardNumber)

	log.Printf("⚡ Executing Core Cache Mitigation...")
	
	// Update user status inside the profile Redis Hash on the fly
	err := rdb.HSet(ctx, profileKey, "status", "frozen").Err()
	if err != nil {
		log.Printf("❌ Failed to freeze account status flags inside Redis: %v\n", err)
		return
	}
	
	log.Printf("🔒 [STATUS: FROZEN] Card profile '%s' locked out inside Redis layer successfully.\n", profileKey)
}